name: flutter_view
description: A new flutter project.

dependencies:
  flutter:
    sdk: flutter

  rxdart: "^0.16.0+1"
  fluro: "^1.2.1"
  firebase_messaging: "^0.1.4"
  redux: "^2.1.1"
  flutter_redux: "^0.3.5"
  redux_epics: "^0.8.0"
  cached_network_image: "^0.3.0"
  flutter_stetho: "^0.0.1"



flutter:
  uses-material-design: true
  assets:
    - assets/flutter-mark-square-64.png
    - assets/flutter_high.png
